const DATE_FORMAT = 'DD-MM-YYYY HH:mm';
const BOOKING_COLLECTION = 'Bookings';
const USERS_COLLECTION = 'Users';
const REVIEWS_COLLECTION = 'Reviews';
const BARBERSHOPS_COLLECTION = 'BarberShops';
const SERVICES_COLLECTION = 'Services';
const BOOKINGS_COLLECTION = 'Bookings';
const REVOKED_TOKENS_COLLECTION = 'RevokedTokens';
const BARBER_DETAILS_COLLECTION = 'BarberDetails';
const CUSTOMER_DETAILS_COLLECTION = 'CustomerDetails';
const CUSTOMER_ROLE = 'Customer';
const BARBER_ROLE = 'Barber';
module.exports = {
    DATE_FORMAT,
    BOOKING_COLLECTION,
    USERS_COLLECTION,
    REVIEWS_COLLECTION,
    BARBERSHOPS_COLLECTION,
    SERVICES_COLLECTION,
    BOOKINGS_COLLECTION,
    REVOKED_TOKENS_COLLECTION,
    BARBER_DETAILS_COLLECTION,
    CUSTOMER_DETAILS_COLLECTION,
    CUSTOMER_ROLE,
    BARBER_ROLE
}