const DATE_FORMAT = 'DD-MM-YYYY HH:mm';
const BOOKING_COLLECTION = 'Bookings';
const USERS_COLLECTION = 'Users';
const REVIEWS_COLLECTION = 'Reviews';
const BARBERSHOPS_COLLECTION = 'BarberShops';
const SERVICES_COLLECTION = 'Services';
const BOOKINGS_COLLECTION = 'Bookings';
const REVOKED_TOKENS_COLLECTION = 'RevokedTokens';
module.exports = {
    DATE_FORMAT,
    BOOKING_COLLECTION,
    USERS_COLLECTION,
    REVIEWS_COLLECTION,
    BARBERSHOPS_COLLECTION,
    SERVICES_COLLECTION,
    BOOKINGS_COLLECTION,
    REVOKED_TOKENS_COLLECTION
}